<?php

return [
    'name' => 'pagination-xdecaro',
    'title' => 'Pagination by xdecaro',
    'group' => 'xdecaro',
    'icon' => '${url:images/icon.svg}',
    'iconSmall' => '${url:images/iconSmall.svg}',
    'element' => true,
    'width' => 500,

    'defaults' => [
        'mode' => 'loadmore',
        'target_mode' => 'auto',
        'target_selector' => '',
        'item_selector' => ':scope > *',
        'pagination_selector' => '.uk-pagination, .pagination, nav[aria-label*="pagination" i], nav[aria-label*="pagin" i]',
        'batch_size' => 4,
        'gallery_initial_size' => 20,
        'gallery_batch_size' => 20,
        'max_loads' => 4,
        'loadmore_text' => '',
        'previous_text' => '',
        'next_text' => '',
        'loading_text' => '',
        'end_text' => '',
        'limit_text' => '',
        'error_text' => '',
        'control_style' => 'text',
        'control_size' => '',
        'control_width' => '',
        'icon' => 'arrow',
        'icon_position' => 'right',
        'custom_background' => '',
        'custom_color' => '',
        'custom_border_color' => '',
        'custom_hover_background' => '',
        'custom_hover_color' => '',
        'custom_hover_border_color' => '',
        'custom_active_background' => '',
        'custom_active_color' => '',
        'custom_border_width' => 1,
        'custom_radius' => 0,
        'threshold' => 500,
        'animation' => 'fade',
        'hide_pagination' => true,
        'update_url' => false,
        'scroll_top' => true,
        'show_end_message' => true,
    ],

    'templates' => [
        'render' => __DIR__ . '/templates/template.php',
    ],

    'fields' => [
        'mode' => [
            'label' => 'Modalità',
            'type' => 'select',
            'options' => [
                'Carica altri' => 'loadmore',
                'Scroll infinito' => 'infinite',
                'Numerica' => 'numeric',
                'Precedente / Successivo' => 'prevnext',
                'Completa — Precedente + numeri + Successivo' => 'full',
            ],
        ],
        'target_mode' => [
            'label' => 'Elemento collegato',
            'description' => 'Collega Pagination a una Grid paginata oppure a una Gallery YOOtheme. Per Gallery vengono gestiti localmente gli elementi già renderizzati.',
            'type' => 'select',
            'options' => [
                'Grid precedente — Automatico' => 'auto',
                'Gallery precedente — Locale' => 'gallery',
                'Elemento tramite ID CSS' => 'selector',
            ],
        ],
        'target_selector' => [
            'label' => 'ID / selettore elemento',
            'description' => 'Assegna un ID alla Grid o al contenitore in Avanzate → ID e inseriscilo qui con #, ad esempio #blog-grid.',
            'attrs' => ['placeholder' => '#blog-grid'],
            'show' => 'target_mode == "selector"',
        ],
        'item_selector' => [
            'label' => 'Selettore elementi',
            'description' => 'Opzione tecnica avanzata. Lascia :scope > * salvo layout particolari.',
        ],
        'pagination_selector' => [
            'label' => 'Selettore paginazione sorgente',
            'description' => 'Per Grid paginate, Pagination usa la paginazione Joomla/YOOtheme come sorgente quando disponibile. Non viene usata in modalità Gallery locale.',
        ],
        'batch_size' => [
            'label' => 'Elementi per caricamento',
            'description' => 'Numero massimo di nuovi elementi aggiunti a ogni clic o attivazione dello scroll infinito.',
            'type' => 'number',
            'attrs' => ['min' => 1, 'step' => 1],
            'show' => 'target_mode != "gallery" && (mode == "loadmore" || mode == "infinite")',
        ],
        'gallery_initial_size' => [
            'label' => 'Elementi iniziali',
            'description' => 'Per Gallery: numero di elementi mostrati subito. La Gallery YOOtheme deve renderizzare tutti gli elementi disponibili.',
            'type' => 'number',
            'attrs' => ['min' => 1, 'step' => 1],
            'show' => 'target_mode == "gallery"',
        ],
        'gallery_batch_size' => [
            'label' => 'Elementi per caricamento',
            'description' => 'Per Gallery: numero di elementi aggiunti a ogni clic o attivazione dello scroll infinito.',
            'type' => 'number',
            'attrs' => ['min' => 1, 'step' => 1],
            'show' => 'target_mode == "gallery" && (mode == "loadmore" || mode == "infinite")',
        ],
        'max_loads' => [
            'label' => 'Numero massimo caricamenti',
            'description' => 'Per Gallery: limita quante volte possono essere mostrati altri elementi. 0 = nessun limite. Predefinito: 4.',
            'type' => 'number',
            'attrs' => ['min' => 0, 'max' => 50, 'step' => 1],
            'show' => 'target_mode == "gallery" && (mode == "loadmore" || mode == "infinite")',
        ],
        'loadmore_text' => [
            'label' => 'Testo Carica altri',
            'description' => 'Lascia vuoto per il testo automatico della lingua del sito. Esempio personalizzato: Carica altri articoli.',
            'show' => 'mode == "loadmore"',
        ],
        'previous_text' => [
            'label' => 'Testo Precedente',
            'description' => 'Lascia vuoto per il testo automatico della lingua del sito.',
            'show' => 'mode == "prevnext" || mode == "full"',
        ],
        'next_text' => [
            'label' => 'Testo Successivo',
            'description' => 'Lascia vuoto per il testo automatico della lingua del sito.',
            'show' => 'mode == "prevnext" || mode == "full"',
        ],
        'loading_text' => [
            'label' => 'Testo caricamento',
            'description' => 'Lascia vuoto per il testo automatico della lingua del sito.',
        ],
        'end_text' => [
            'label' => 'Testo fine elenco',
            'description' => 'Usato da Carica altri e Scroll infinito quando non esistono altri elementi.',
            'show' => 'mode == "loadmore" || mode == "infinite"',
        ],
        'limit_text' => [
            'label' => 'Testo limite raggiunto',
            'description' => 'Per Gallery: mostrato se viene raggiunto il numero massimo di caricamenti ma restano altri elementi. Lascia vuoto per il testo automatico.',
            'show' => 'target_mode == "gallery" && (mode == "loadmore" || mode == "infinite")',
        ],
        'error_text' => [
            'label' => 'Testo errore',
            'description' => 'Lascia vuoto per il testo automatico della lingua del sito.',
        ],
        'control_style' => [
            'label' => 'Stile controlli',
            'type' => 'select',
            'options' => [
                'Default' => 'default',
                'Primary' => 'primary',
                'Secondary' => 'secondary',
                'Danger' => 'danger',
                'Text' => 'text',
                'Link' => 'link',
                'Personalizzato' => 'custom',
            ],
        ],
        'control_size' => [
            'label' => 'Dimensione controlli',
            'type' => 'select',
            'options' => [
                'Default' => '',
                'Small' => 'small',
                'Large' => 'large',
            ],
        ],
        'control_width' => [
            'label' => 'Larghezza pulsante',
            'type' => 'select',
            'options' => [
                'Automatica' => '',
                '100%' => '1-1',
            ],
            'show' => 'mode == "loadmore"',
        ],
        'icon' => [
            'label' => 'Icona',
            'type' => 'select',
            'options' => [
                'Nessuna' => 'none',
                'Freccia' => 'arrow',
                'Chevron' => 'chevron',
                'Plus' => 'plus',
            ],
        ],
        'icon_position' => [
            'label' => 'Posizione icona',
            'type' => 'select',
            'options' => [
                'Destra' => 'right',
                'Sinistra' => 'left',
            ],
            'show' => 'icon != "none"',
        ],
        'custom_background' => [
            'label' => 'Sfondo',
            'type' => 'color',
            'show' => 'control_style == "custom"',
        ],
        'custom_color' => [
            'label' => 'Testo',
            'type' => 'color',
            'show' => 'control_style == "custom"',
        ],
        'custom_border_color' => [
            'label' => 'Bordo',
            'type' => 'color',
            'show' => 'control_style == "custom"',
        ],
        'custom_hover_background' => [
            'label' => 'Hover — sfondo',
            'type' => 'color',
            'show' => 'control_style == "custom"',
        ],
        'custom_hover_color' => [
            'label' => 'Hover — testo',
            'type' => 'color',
            'show' => 'control_style == "custom"',
        ],
        'custom_hover_border_color' => [
            'label' => 'Hover — bordo',
            'type' => 'color',
            'show' => 'control_style == "custom"',
        ],
        'custom_active_background' => [
            'label' => 'Pagina attiva — sfondo',
            'type' => 'color',
            'show' => 'control_style == "custom" && (mode == "numeric" || mode == "full")',
        ],
        'custom_active_color' => [
            'label' => 'Pagina attiva — testo',
            'type' => 'color',
            'show' => 'control_style == "custom" && (mode == "numeric" || mode == "full")',
        ],
        'custom_border_width' => [
            'label' => 'Spessore bordo (px)',
            'type' => 'number',
            'attrs' => ['min' => 0, 'max' => 6, 'step' => 1],
            'show' => 'control_style == "custom"',
        ],
        'custom_radius' => [
            'label' => 'Raggio angoli (px)',
            'type' => 'number',
            'attrs' => ['min' => 0, 'max' => 50, 'step' => 1],
            'show' => 'control_style == "custom"',
        ],
        'threshold' => [
            'label' => 'Distanza attivazione (px)',
            'description' => 'Per Scroll infinito. Avvia il caricamento prima di raggiungere il fondo.',
            'type' => 'range',
            'attrs' => ['min' => 0, 'max' => 1500, 'step' => 50],
            'show' => 'mode == "infinite"',
        ],
        'animation' => [
            'label' => 'Animazione elementi',
            'type' => 'select',
            'options' => [
                'Nessuna' => 'none',
                'Fade' => 'fade',
                'Slide' => 'slide',
            ],
            'show' => 'mode == "loadmore" || mode == "infinite"',
        ],
        'hide_pagination' => [
            'label' => 'Nascondi paginazione originale',
            'type' => 'checkbox',
            'text' => 'Nascondi la Pagination Joomla/YOOtheme usata come sorgente dati',
            'show' => 'target_mode != "gallery"',
        ],
        'update_url' => [
            'label' => 'Aggiorna URL',
            'type' => 'checkbox',
            'text' => 'Aggiorna l’indirizzo alla pagina visualizzata senza ricaricare',
            'show' => 'target_mode != "gallery"',
        ],
        'scroll_top' => [
            'label' => 'Torna all’elemento',
            'type' => 'checkbox',
            'text' => 'Dopo una paginazione numerica torna all’inizio della Grid o Gallery',
            'show' => 'mode == "numeric" || mode == "prevnext" || mode == "full"',
        ],
        'show_end_message' => [
            'label' => 'Messaggio finale',
            'type' => 'checkbox',
            'text' => 'Mostra un messaggio quando sono stati caricati tutti gli elementi o viene raggiunto il limite',
            'show' => 'mode == "loadmore" || mode == "infinite"',
        ],
        'margin_top' => '${builder.margin_top}',
        'margin_bottom' => '${builder.margin_bottom}',
        'text_align' => '${builder.text_align_justify}',
        'text_align_breakpoint' => '${builder.text_align_breakpoint}',
        'text_align_fallback' => '${builder.text_align_justify_fallback}',
        'visibility' => '${builder.visibility}',
        'name' => '${builder.name}',
        'status' => '${builder.status}',
        'id' => '${builder.id}',
        'class' => '${builder.cls}',
        'attributes' => '${builder.attrs}',
        'css' => [
            'label' => 'CSS',
            'type' => 'editor',
            'editor' => 'code',
            'mode' => 'css',
            'attrs' => ['debounce' => 500],
        ],
    ],

    'fieldset' => [
        'default' => [
            'type' => 'tabs',
            'fields' => [
                [
                    'title' => 'Contenuto',
                    'fields' => [
                        'mode',
                        'target_mode',
                        'target_selector',
                        'gallery_initial_size',
                        'batch_size',
                        'gallery_batch_size',
                        'max_loads',
                    ],
                ],
                [
                    'title' => 'Impostazioni',
                    'fields' => [
                        [
                            'label' => 'Testi',
                            'type' => 'group',
                            'fields' => ['loadmore_text', 'previous_text', 'next_text', 'loading_text', 'end_text', 'limit_text', 'error_text'],
                        ],
                        [
                            'label' => 'Aspetto',
                            'type' => 'group',
                            'fields' => ['control_style', 'control_size', 'control_width', 'icon', 'icon_position'],
                        ],
                        [
                            'label' => 'Stile personalizzato',
                            'type' => 'group',
                            'fields' => [
                                'custom_background',
                                'custom_color',
                                'custom_border_color',
                                'custom_hover_background',
                                'custom_hover_color',
                                'custom_hover_border_color',
                                'custom_active_background',
                                'custom_active_color',
                                'custom_border_width',
                                'custom_radius',
                            ],
                        ],
                        [
                            'label' => 'Comportamento',
                            'type' => 'group',
                            'fields' => ['threshold', 'animation', 'hide_pagination', 'update_url', 'scroll_top', 'show_end_message'],
                        ],
                        [
                            'label' => 'Avanzate sorgente',
                            'type' => 'group',
                            'fields' => ['item_selector', 'pagination_selector'],
                        ],
                        [
                            'label' => 'Layout',
                            'type' => 'group',
                            'fields' => [
                                'margin_top',
                                'margin_bottom',
                                'text_align',
                                'text_align_breakpoint',
                                'text_align_fallback',
                                'visibility',
                            ],
                        ],
                    ],
                ],
                '${builder.advanced}',
            ],
        ],
    ],
];
